# Generated by Django 4.2.16 on 2026-04-16 08:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Issue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title_hy",
                    models.CharField(max_length=255, verbose_name="Title (Armenian)"),
                ),
                (
                    "title_en",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Title (English)"
                    ),
                ),
                (
                    "description_hy",
                    models.TextField(verbose_name="Description (Armenian)"),
                ),
                (
                    "description_en",
                    models.TextField(blank=True, verbose_name="Description (English)"),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("road", "Road / Ճանապարհ"),
                            ("water", "Water / Ջուր"),
                            ("electricity", "Electricity / Էլեկտրաէներգիա"),
                            ("waste", "Waste / Աղբ"),
                            ("safety", "Safety / Անվտանգություն"),
                            ("other", "Other / Այլ"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending / Սպասվում է"),
                            ("under_review", "Under Review / Քննության փուլ"),
                            ("in_progress", "In Progress / Ընթացքի մեջ"),
                            ("completed", "Completed / Ավարտված"),
                            ("rejected", "Rejected / Մերժված"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "area",
                    models.CharField(
                        choices=[
                            ("city", "Kapan City / Կապան քաղաք"),
                            ("village", "Village / Կապանի շրջանի գյուղեր"),
                        ],
                        default="city",
                        max_length=10,
                    ),
                ),
                ("village_name", models.CharField(blank=True, max_length=100)),
                ("latitude", models.FloatField(default=39.2067)),
                ("longitude", models.FloatField(default=46.4058)),
                ("location_address", models.CharField(blank=True, max_length=500)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="issues/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("upvote_count", models.PositiveIntegerField(default=0)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reported_issues",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Issue",
                "verbose_name_plural": "Issues",
                "ordering": ["-upvote_count", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_status", models.CharField(max_length=20)),
                ("new_status", models.CharField(max_length=20)),
                ("note", models.TextField(blank=True)),
                ("changed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_history",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "verbose_name": "Status History",
                "verbose_name_plural": "Status Histories",
                "ordering": ["changed_at"],
            },
        ),
        migrations.CreateModel(
            name="IssueComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
