# Generated by Django 4.2.16 on 2026-05-04 15:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="area",
            field=models.CharField(
                choices=[
                    ("city", "Kapan City / Կապան քաղաք"),
                    ("village", "Village / Գյուղ"),
                ],
                default="city",
                max_length=10,
            ),
        ),
        migrations.CreateModel(
            name="IssueImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="issues/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "issue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="extra_images",
                        to="issues.issue",
                    ),
                ),
            ],
            options={
                "ordering": ["uploaded_at"],
            },
        ),
    ]
