# Generated by Django 4.2.16 on 2026-04-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_user_doc_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("hy", "Armenian"),
                            ("fr", "French"),
                            ("en", "English"),
                        ],
                        db_index=True,
                        default="hy",
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Lower numbers are displayed first.",
                        verbose_name="Display Order",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Section Title"),
                ),
                ("body", models.TextField(verbose_name="Section Body")),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive sections are hidden from the About page.",
                        verbose_name="Active",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "About Section",
                "verbose_name_plural": "About Sections",
                "ordering": ["language", "order"],
                "indexes": [
                    models.Index(
                        fields=["language", "is_active"], name="about_lang_active_idx"
                    )
                ],
            },
        ),
    ]
